CONTIKI_PROJECT = hello-world
all: $(CONTIKI_PROJECT)



TARGET = openmote
BOARD = openmote-b

MAKE_MAC = MAKE_MAC_TSCH

MODULES += os/services/shell


CONTIKI = ../..
include $(CONTIKI)/Makefile.include
