CONTIKI_PROJECT = hello-world
all: $(CONTIKI_PROJECT)

MAKE_MAC = MAKE_MAC_TSCH
MODULES += os/services/shell

TARGET = openmote
BOARD = openmote-b

CONTIKI = ../../../..
include $(CONTIKI)/Makefile.include
